stages:
  - test
  - build

cache:
  paths:
  - node_modules/

test:
  stage: test

  image: node:10.16.3-alpine

  variables:
    CI: "true"

  script:
    - yarn
    - yarn test

build:
  stage: build

  image: docker:stable

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    ECR_IMAGE: 695694022540.dkr.ecr.ap-southeast-2.amazonaws.com/base-admin/base-admin

  services:
    - docker:dind

  before_script:
    - apk update
    - apk add python3
    - pip3 install --upgrade awscli
    - $(aws ecr get-login --region ap-southeast-2 --no-include-email)
    - aws ecr --region ap-southeast-2 describe-repositories --repository-names base-admin/base-admin || aws ecr --region ap-southeast-2 create-repository --repository-name base-admin/base-admin

  script:
    - docker build -t base-admin .
    - docker tag base-admin ${ECR_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${ECR_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker tag base-admin ${ECR_IMAGE}
    - docker push ${ECR_IMAGE}
