stages:
  - test
  - build

cache:
  paths:
  - node_modules/

test:
  stage: test

  image: node:10.16.3-alpine

  variables:
    CI: "true"

  script:
    - yarn
    - yarn test

build:
  stage: build

  image: docker:stable

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    REPO_NAME: base-admin/base-admin
    REGION: ap-southeast-2
    DESCRIBE_CMD: aws ecr --region ${REGION} describe-repositories --repository-names ${REPO_NAME}
    CREATE_CMD: aws ecr --region ${REGION} create-repository --repository-name ${REPO_NAME}

  services:
    - docker:dind

  before_script:
    - apk update
    - apk add python3
    - apk add jq
    - pip3 install --upgrade awscli
    - $(aws ecr get-login --region ap-southeast-2 --no-include-email)
    - ${DESCRIBE_CMD} || ${CREATE_CMD}
    - export ECR_URI=$(${DESCRIBE_CMD} | jq '.repositories[0].repositoryUri')

  script:
    - echo ${ECR_URI}
