stages:
  - build
  - test

cache:
  paths:
  - node_modules/

build:
  stage: build
  image: node:10.16.3-alpine

  script:
    - yarn
    - yarn build

test:
  stage: test

  variables:
    CI: "true"

  script:
    - yarn test
