name: Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get version from package.json
        run: echo NPM_PACKAGE_VERSION=v$(cat package.json | jq -r .version) >> $GITHUB_ENV

      - name: Print version
        run: echo $NPM_PACKAGE_VERSION

      - name: Print tags
        run: git tag

      - name: Debug grep tags
        run: git tag | grep $NPM_PACKAGE_VERSION

      - name: Tag new version
        run: |
          if [ -z $(git tag | grep $NPM_PACKAGE_VERSION) ]; then
            git tag $NPM_PACKAGE_VERSION;
            git push --tags
          fi
