name: Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from package.json
        run: echo NPM_PACKAGE_VERSION=v$(cat package.json | jq -r .version) >> $GITHUB_ENV

      - name: Print version
        run: echo $NPM_PACKAGE_VERSION
